### ISSUE TITLE
Will ESP NOW Mesh Support 1000 nodes Connected in a line(Street Light) each 50-100 meter apart

### ISSUE THREAD

**Issue by mightChamp** [arttupii/EspNowFloodingMesh#7]

**Comment by lmachineone** [comment]
I created my own my mesh protocol on top of esp now, that supports an almost infinite numbers of connected devices with up to 2 seconds of latency. Let me know if interested so we can collaborate. Hit me on my business email, lucas@quantumleapsoftware.pro

**Comment by mightChamp** [comment]
Thanks @perinm , Will your mesh protocol supports 1000 nodes Connected in a line(Street Light) each 50-100 meter apart. Means Gateway will able to send data to last 1000th node and there will be 1000 hops? and How much time will take to send to 1000th node?, Answer this So we can think for collaborate.

**Comment by lmachineone** [comment]
> Thanks @perinm , Will your mesh protocol supports 1000 nodes Connected in a line(Street Light) each 50-100 meter apart. Means Gateway will able to send data to last 1000th node and there will be 1000 hops? and How much time will take to send to 1000th node?, Answer this So we can think for collaborate.

Yes. Depends on the esp model you are using, I used a specific $5 Esp32 from aliexpress which reaches 300 meters without line sight. Possibly 500 meters with line of sight. I developed for agriculture, so my project was for mango trees, a soil moisture sensor. Depends more on how big is the data you want from each device, my protocol only supports a max 250 bytes, but from 250 bytes some are necessary to make the mesh protocol work, the less bytes you need, the more devices we can support.

**Comment by mightChamp** [comment]
Thanks @perinm , My Issue is not range, latency and data bytes(max  50 bytes), Issue is that my all 1000 nodes are in a line, and each 50 meter apart, Imagine  Street lights each 50 meter apart line (50km line). There is only one gateway(root node) at start.
So will you think system will work with your code?

**Comment by lmachineone** [comment]
> Thanks @perinm , My Issue is not range, latency and data bytes(max  50 bytes), Issue is that my all 1000 nodes are in a line, and each 50 meter apart, Imagine  Street lights each 50 meter apart line (50km line). There is only one gateway(root node) at start.
> So will you think system will work with your code?

Depends. Is a max of 50s latency OK with you? I think we can do 5s in this scenario too, but just trying to draw worst case scenario you know. The code is ready too.

**Comment by mightChamp** [comment]
latency is ok, But Is this robust, I mean That It should have to be full feedback system and should have retry mechanisms if send fail, and concurrency of data may be there, as no of devices can send data to gateway, at same time. So Will you Your Code can handle this.

**Comment by lmachineone** [comment]
yes.
But you need the full solution.
There are 4 components:
- an esp code for gateway
- an esp code for nodes,
- one python api ingestion for data
- a timeseries db, in this case influxdb

This solution was made just for data collection from sensors, would you like to act also?

There is failover, and retry mechanism, any node can go down, and things will continue working, nodes can have any ID, and you are able to update each esp software through wifi access point they create, protected by password.

With just 50 bytes of necessary data for message you can support a lot more devices than just 1K.

For me to continue talking we will need to move the conversation out of here, otherwise there is sensitive IP in risk.

**Comment by mightChamp** [comment]
Ok Dear thanks for info, I am still finding Some other solution, will let you know If I need your support.

**Comment by lmachineone** [comment]
> Ok Dear thanks for info, I am still finding Some other solution, will let you know If I need your support.

Can you elaborate what is missing in this solution so we could do something? I built this for my previous attempt as startup founder so this part is battle proven ready for most scenarios. Dealt with many trees as obstacles and working very good.

My plan is to build an open source framework on top of it, non-profit.

**Comment by mightChamp** [comment]
I am looking for more standardized solution like ZigBee.

**Comment by lmachineone** [comment]
Not possible with your restrictions. That's why I created this. If you
manage to make it work with zigbee let me know.

**Comment by lmachineone** [comment]
Have you heard of esp wifi lr? That's what I used, you can reach more than a km with it.

**Comment by lmachineone** [comment]
Worked on byte level, other solutions simply won't cut the work, sadly. With the way I coded I just need a broadcast esp now 0message, so no handshakes involved. But still keeping secure.

**Comment by mightChamp** [comment]
> Have you heard of esp wifi lr? That's what I used, you can reach more than a km with it.

Yes I have tested it, but in urban areas practically you will get nearly 100 meter only. and I have select Zigbee to develop, as it is suggested by expressif experts.
